FROM python:3.9-slim-buster

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt

WORKDIR /app
COPY z_mock_live_order.py /app/
COPY Rest_Info.csv /app/

CMD [ "python", "./z_mock_live_order.py" ]