FROM python:3.9-slim-buster

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt

WORKDIR /app
COPY Order_history.csv /app/
COPY Rest_Info.csv /app/
COPY model.py /app/
COPY server.py /app/

CMD [ "python", "./server.py" ]